name: E2ETest

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  e2e-test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          path: src/github.com/kubeflow/katib

      - name: create kind cluster
        uses: helm/kind-action@v1.0.0-rc.1
        with:
          version: v0.8.1
          node_image: kindest/node:v1.16.15
          cluster_name: kind-cluster-v1.16.15
          config: src/github.com/kubeflow/katib/kind-cluster.yaml
          kubeconfig: /kubeconfig

      - name: deploy-katib
        run: |
          make deploy
          TIMEOUT=120
          PODNUM=$(kubectl get deploy -n kubeflow | grep -v NAME | wc -l)
          until kubectl get pods -n kubeflow | grep Running | [[ $(wc -l) -eq $PODNUM ]]; do
            echo Pod Status $(kubectl get pods -n kubeflow | grep "1/1" | wc -l)/$PODNUM
            sleep 10
            TIMEOUT=$((TIMEOUT - 1))
            if [[ $TIMEOUT -eq 0 ]]; then
              echo "NG"
              kubectl get pods -n kubeflow
              exit 1
            fi
          done
          kubectl get pods -n kubeflow
